@startuml
left to right direction

actor Usuario
actor Administrador
database Db

rectangle "Sistema Carrito de Compras" {
    (Registrarse)
    (Iniciar Sesión)
    (Ver Catálogo de Productos)
    (Agregar Producto al Carrito)
    (Ver Carrito)
    (Modificar Carrito)
    (Eliminar Producto del Carrito)
    (Confirmar Compra)
    (Ver Factura)
    (Gestionar Productos)
    (Ver Reportes de Ventas)
}

Db -> "Sistema Carrito de Compras"

Usuario -- (Registrarse)
(Registrarse) .> (Iniciar Sesión) : <<include>>
Usuario -- (Iniciar Sesión)
(Iniciar Sesión) .> (Ver Catálogo de Productos) : <<include>>
Usuario -- (Ver Catálogo de Productos)
(Ver Catálogo de Productos) --> (Agregar Producto al Carrito)
Usuario -- (Agregar Producto al Carrito)
Usuario -- (Ver Carrito)
(Ver Carrito) .> (Modificar Carrito) : <<extend>>
(Ver Carrito) .> (Eliminar Producto del Carrito) : <<extend>>
Usuario -- (Confirmar Compra)
(Confirmar Compra) .> (Ver Factura) : <<include>>

Administrador -- (Iniciar Sesión)
Administrador -- (Gestionar Productos)
Administrador -- (Ver Reportes de Ventas)

@enduml